
import streamlit as st
from openai import OpenAI
import time

st.set_page_config(page_title="GrokMint.ai v5.0", page_icon="🌟", layout="wide")

st.markdown("""
<style>
    .main {background: linear-gradient(135deg, #FF9933, #138808, #FFFFFF); color: #000;}
    .hero {font-size: 52px; font-weight: bold; text-align: center; margin-bottom: 10px;}
    .btn {background:#FF9933 !important; color:black !important; font-size:28px; border-radius:25px; height:80px; font-weight:bold;}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="hero">GrokMint.ai v5.0<br>The New AI Era is Live</p>', unsafe_allow_html=True)
st.caption("Powered by real Grok API • UPI 7889257767 • Compliant")

# Load real Grok API key from secrets
api_key = st.secrets.get("XAI_API_KEY", None)

if not api_key:
    st.error("xAI API key not found in secrets. Add it in Streamlit app settings.")
    st.stop()

client = OpenAI(
    api_key=api_key,
    base_url="https://api.x.ai/v1"
)

idea = st.text_area("Describe your idea in Hindi or English", 
                    placeholder="Bhai Meesho kurti agent bana do jo SEO descriptions, images aur WhatsApp bot de...", 
                    height=150)

if st.button("🌟 LAUNCH MY AGENT — REAL GROK POWER", type="primary", use_container_width=True):
    if not idea.strip():
        st.error("Please describe your idea")
    else:
        with st.spinner("Grok-4.1 is building your real agent..."):
            try:
                response = client.chat.completions.create(
                    model="grok-beta",  # or "grok-4.1-fast" if you have access
                    messages=[
                        {"role": "system", "content": """
You are GrokMint Agent Builder — expert at creating powerful AI agents.
Generate:
1. Complete system prompt for the user's idea
2. 3–5 sample input/output pairs
3. How to use it on WhatsApp/Instagram
4. Monetization tips
Always end with: AI-Generated by GrokMint.ai v5.0 powered by Grok 4.1 [timestamp]
                        """},
                        {"role": "user", "content": idea}
                    ],
                    temperature=0.7,
                    max_tokens=1500
                )

                result = response.choices[0].message.content

                st.balloons()
                st.success("✅ Real Grok Agent Created!")
                st.markdown("**Your Custom Agent (powered by real Grok)**")
                st.text_area("Full Agent Output", result, height=500)
                st.info("Copy above prompt and use in Grok chat. Unique bots & payments coming next.")
                st.button("Share & Earn", type="primary", use_container_width=True)

            except Exception as e:
                st.error(f"Grok API error: {str(e)}\nCheck key/balance/model name in console.x.ai")

st.subheader("Earnings")
st.metric("Withdrawable Now", "₹0 (real-time)", "to UPI 7889257767")

st.caption("Real Grok API • Open Source • Money printing active")